### ISSUE TITLE
Ein paar Vorschläge

### ISSUE THREAD

**Issue by stonerl** [MariusE/Soundflower-Ultraschall-Edition#1]
Hallo Marius,

ich habe mir mal, nachdem ich Soundflower in homebrew-cask eingepflegt habe, noch ein paar Dinge angeschaut.
1. Hab ich mir mal die Installationshistorie angeschaut:

com.cycling74.soundflowerUltraschallEdition.preflight.pkg
com.cycling74.soundflower.pkg
com.cycling74.soundflowerUltraschallEdition.ReadMe.pkg
com.cycling74.soundflowerUltraschallEdition.License.pkg
com.cycling74.soundflowerUltraschallEdition.UninstallSoundflower.pkg
com.cycling74.soundflowerUltraschallEdition.postflight.pkg

Wenn du 

"com.cycling74.soundflower.pkg" 

noch in 

"com.cycling74.soundflowerUltraschallEdition.pkg" 

umbenennen könntest wäre dass super.
1. Die Kernelerweiterung lautet wie folgt:

"/System/Library/Extensions/Soundflower.kext"

wenn du diese in:

/System/Library/Extensions/SoundflowerUltraschallEdition.kext

oder ähnlich umbennen könntetst wäre dass auch klasse. Analog dazu sollte die Bundle-ID von:

com.Cycling74.driver.Soundflower

in

com.Cycling74.driver.SoundflowerUltraschallEdition

umbenannt werden.
1. Der Ordner welcher im Application-Ordner landet sollte wenn möglich auch in Soundflower-UltraschallEdition ö.Ä. umbenannt werden.

Dadurch währe ein klare Trennung zwischen dem originalen Soundflower und der UltraschallEdition gewährleistet. Ich gehe zwar nicht davon aus, dass jemand beide Versionen im Einsatz hat, aber sicher ist sicher.

Gruß

Toni

**Comment by MariusE** [comment]
das klingt nach einer guten Idee.
Werde ich bei nächster Gelegenheit umsetzen.

Danke für den Tipp
