### ISSUE TITLE
Yosemite-kompatibel?

### ISSUE THREAD

**Issue by Suven** [MariusE/Soundflower-Ultraschall-Edition#2]
Hi,

Ich versuche gerade zum ersten Mal Soundflower zu installieren, kann aber leider das Kernelmodul nicht laden.

Beim Versuch `sudo kextload /System/Library/Extensions/Soundflower.kext` auszuführen, bekomme ich den syslog-Eintrag:

```
10/08/14 21:29:40,546 com.apple.kextd[19]: ERROR: invalid signature for com.Cycling74.driver.Soundflower, will not load
```

Weder in den Soundoptionen, noch im Midi Setup sehe ich zusätzliche Geräte.
In den Sicherheitseinstellungen habe ich das Ausführen von Software von überall aus erlaubt.

Könnte das an Yosemite liegen, oder vergesse ich etwas wesentliches?

**Comment by MariusE** [comment]
Es ist definitiv nicht 10.10 kompatibel.  Das liegt daran, dass unter 10.10 - wohl - nur noch signierte Extensions laufen. Und an diese Signatur kommt man leider nicht ganz ohne Umwege. Wir sind dabei das zu lösen.

**Comment by Suven** [comment]
Hi,

danke für die Antwort. Ist immer total doof wenn man kurz darauf selbst eine mögliche Lösung postet, auf diese bin ich nun aber doch noch gestoßen.

```
 sudo nvram boot-args="kext-dev-mode=1"
```

Keine Ahnung ob das wirklich so eine super Idee ist, es klappt jedenfalls und danach kann man es ja wieder auf 0 setzen.

**Comment by MariusE** [comment]
Das ist halt eine Überbrückung von Sicherheitsfunktionen. Aber damit funktioniert es. 

das funktioniert also wenn man es danach wieder zurücksetzt weiterhin?  auch beim Reboot?  das wäre interessant!

**Comment by Suven** [comment]
Ja, genau so ist es
